// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg2jELpZV_l1mItYO8y2JO93rhQTiGiZk',
    appId: '1:55596909847:web:d09357b6713bc25bbe6352',
    messagingSenderId: '55596909847',
    projectId: 'mesaj-70cc2',
    authDomain: 'mesaj-70cc2.firebaseapp.com',
    storageBucket: 'mesaj-70cc2.firebasestorage.app',
    measurementId: 'G-2KNNYNDPWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR995TqJ0yp1PQ5pjPqBA8NuS0QgbJwKs',
    appId: '1:55596909847:android:263c4f2c1d1c7710be6352',
    messagingSenderId: '55596909847',
    projectId: 'mesaj-70cc2',
    storageBucket: 'mesaj-70cc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY8mEmgdtxFnwHvXNRw32sMVTfmTwiSzo',
    appId: '1:55596909847:ios:bd396e50ace8f2d5be6352',
    messagingSenderId: '55596909847',
    projectId: 'mesaj-70cc2',
    storageBucket: 'mesaj-70cc2.firebasestorage.app',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY8mEmgdtxFnwHvXNRw32sMVTfmTwiSzo',
    appId: '1:55596909847:ios:bd396e50ace8f2d5be6352',
    messagingSenderId: '55596909847',
    projectId: 'mesaj-70cc2',
    storageBucket: 'mesaj-70cc2.firebasestorage.app',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg2jELpZV_l1mItYO8y2JO93rhQTiGiZk',
    appId: '1:55596909847:web:a7aec0b1be4f03fcbe6352',
    messagingSenderId: '55596909847',
    projectId: 'mesaj-70cc2',
    authDomain: 'mesaj-70cc2.firebaseapp.com',
    storageBucket: 'mesaj-70cc2.firebasestorage.app',
    measurementId: 'G-HFXVRE1S6K',
  );
}
